version: '1.0'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:management
    environment:
       - RABBITMQ_DEFAULT_USER=cmilheim
       - RABBITMQ_DEFAULT_PASS=rmqpassword
    ports:
       # AMQP protocol port
       - 5672:5672
       # HTTP management UI
       - 15672:15672

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: 'cmilheim'
      MYSQL_PASSWORD: 'userpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  mongodb_data_container:
  my-db: